### ISSUE TITLE
Workflow issues

### ISSUE THREAD

**Issue by sreichel** [OpenMage/magento-lts#2770]
### Summary (*)

Just for me ... (to make checks bit quicker)

- [x] if composer files have changed BUT validation fails, nothing else should run (1)
- [x] move phpstan behind cs-checks (in case of cs-errors theres no need to run it) (2)
- [x] run PhpUnit and complete Php syntax check only on workflow update and schedule - #2765
- [x] add JS validation - #2644
- [x] add PHPMD - #2771
- [ ] run other checks when composer is skipped
- [ ] update phpstorm metafiles - #2009

#### Fix suppressed errors!

- [ ] fix phpstan baseline :nerd_face: 
- [ ] fix PhpCompatibility checks
- [ ] add useful ECG standard config (just for test right now)

### Examples (*)

1. https://github.com/OpenMage/magento-lts/actions/runs/3591411736
2. https://github.com/OpenMage/magento-lts/actions/runs/3594674118

### Proposed solution

Update workflow ... ;)
