### ISSUE TITLE
[WIP] Project cleanup?

### ISSUE THREAD

**Issue by sreichel** [OpenMage/magento-lts#416]
I doubt there will be a M1.10 with bigger code changes, so why not to tidy up this project?

**Cleanup:**

- [ ] remove dead code
  - [x] unused libraries (some `Zend` as @colinmollenhour already suggested #374) *
    - [ ] `lib/Mage/?`
    - [x] `lib/PEAR` (#952)
    - [x] `lib/Zend/?`
  - [ ] unused modules
    - [x] `Mage_Compiler` (#534)
    - [x] `Mage_Connect` (#952)
    - [x] `Mage_GoogleBase` (deprecated after 1.5.1.0) (#1002)
    - [ ] `Mage_Usa` (_now the process of creating the label is on DHL side_)
    - [x] `Mage_XmlConnect` (disabled by default, extends `Enterprise_`) (#1040)
    - [x] `Phoenix_Moneybookers` (#1044)
  - [ ] unused methods
  - [ ] deprecated methods
  - [ ] deprecated classes (`Mysql4`)
  - [x] remove downloader (#952)
- [x] general fixes
  - [x] like session validtion (#406)
  - [x] unused/undefined method/variable (e.g. #436)
- [ ]  check if overriden classes are newer

**"Improvements _beyond bug fixes_"** (features)**:**

- [ ] improve layout system
  - [ ] Aoe_Layout (#292)
  - [x] N98_LayoutHelper (#1051, netz98/N98_LayoutHelper#12)
- [ ] improve config loading (system.xml)
  - [x] load order _child -> parent_ (#259)
  - [ ] add default/values to config
  - [ ] add field validation
- [ ] improve permission system
  - [ ] add check for all massactions (#437)
- [ ] improve modularization
  - [ ] _see comment @LeeSaferite_
- [ ] improve event system
  - [ ] add mor named events  (#249 needs update)
- [x] add translation CSV for changed/added tranlations (#358)
- [x] Stampede-Resistant Config Cache (#422)

**"full" IDE support / DOC block updates**

- [x] DOC block updates
  - [x] Admin (#778)
  - [ ] Adminhtml (no PR, big one)
  - [x] AdminNotification (#695)
  - [x] Api (#693)
  - [x] Api2 (#779)
  - [ ] Authorizenet (#1139)
  - [x] Backup (no PR)
  - [x] Bundle (#782)
  - [x] Captcha (#698)
  - [x] Catalog (#783)
  - [x] CatalogIndex (#781)
  - [x] CatalogInventory (#780)
  - [x] CatalogRule (#777)
  - [x] CatalogSearch (#776)
  - [ ] Centinel (no PR)
  - [x] Checkout (#775)
  - [x] <s>Connect</s>  (removed, see #952)
  - [x] Cms (#694)
  - [x] ConfigurableSwatches (#774)
  - [x] Contacts (#699)
  - [x] Core (#702)
  - [x] Cron (#697)
  - [x] CurrencySymbol (#708)
  - [x] Customer (#701)
  - [ ] Dataflow (no PR)
  - [x] Directory (#773)
  - [x] Downloadable (#772)
  - [x] Eav (#771)
  - [x] GiftMessage (#770)
  - [ ] GoogleAnalytics (no PR)
  - [x] <s>GoogleBase</s> (removed, see #1002)
  - [ ] GoogleCheckout (no PR)
  - [x] ImportExport (#769)
  - [x] Index (#768)
  - [ ] Install (no PR)
  - [x] Log (#767)
  - [x] Media (#766)
  - [x] Newsletter (#765)
  - [x] Oauth (#764)
  - [x] Page (#762)
  - [x] PageCache (#761)
  - [ ] Paygate (no PR)
  - [x] Payment (#760)
  - [ ] Paypal (no PR)
  - [ ] PaypalUk (no PR)
  - [x] Persistent (#759)
  - [x] Poll (#758)
  - [x] ProductAlert (#757)
  - [x] Rating (#756)
  - [x] Reports (#755)
  - [x] Review (#754)
  - [x] Rss (#1406)
  - [x] Rule (#753)
  - [x] Sales (#751)
  - [x] SalesRule (#750)
  - [x] Sendfriend (#749)
  - [x] Shipping (#748)
  - [x] Sitemap (#747)
  - [x] Tag (#746)
  - [x] Tax (#745)
  - [x] Uploader (no PR)
  - [ ] Usa (no PR)
  - [x] Weee (#744)
  - [x] Widget (#743)
  - [x] Wishlist (#742)
  - [x] <s>XmlConnect</s> (removed, see #1040)
  - [x] Varien (1) (#703, not complete)
  - [x] Zend (no PR)

**development**

- [ ] add UnitTests
- [x] PHP7 "optimized" branch
- [ ] backport M2 fixes (e.g. #351)

----

> However, I would also consider this project to be more of a "power-user" derivative and think that dropping support for old versions and even making PHP 7 the minimum would not be unreasonable. 

I'd keep/update the master (`1.9.3.x`) branch as usual to not break anything, but start a new `1.9.3.x-dev` that includes also BC breaking changes  (like PHP7 required, or removing deprecated methods)

**Comment by seansan** [comment]
- [ ] Optimize queries where possible? (add/remove indexes)
- [ ] DB optimzations (other then indexes)

ps. would not remove downloader as of yet

**Comment by LeeSaferite** [comment]
I think the Venn diagram of power users and connect users would be quite small.

**Comment by LeeSaferite** [comment]
FWIW, I'm totally on board with this idea. I would love to see some real love applied to the M1 codebase.

A project I've started multiple times and would love to complete is fixing the broken modularization of M1. One aspect of that is controller locations. Since in the early days you could only have one module per shortname, they moved all the admin code into the Mage_Adminhtml module. After they added the ability to register multiple modules on a shortname (I like to think my module pushed them to do that, hah!), they started adding admin related controllers in their respective modules, but they never moved the original controllers to their correct modules. Moving them is fairly easy. And we can replace the moved controllers with stubs that call to the correct controller *and* log a deprecation warning. Another aspect of the modularization issue is underclared and circular deps in the modules. That's a tad harder to resolve, but is still possible. I know that M1 is an EOL platform at this point, but I think with some community effort it could live on in parallel for quite a while.

**Comment by sreichel** [comment]
> A project I've started multiple times and would love to complete is fixing the broken modularization of M1. One aspect of that is controller locations.

W'd like to see this ... but how to start? Guess waiting for a todo lit will take ages, so why not start a `feature` or `dev` branch and start commiting?

**Comment by edannenberg** [comment]
Intrigued by #435 I ran PhpStorm's code inspection on the repo. Oh my. :) I guess a lot of them are to be expected due to the custom aspects of Magento's core but def. plenty of code smells like broken function signature calls.

Was only interested in undefined vars like in the linked issue today, not too bad, but still a few that should be looked at. (untick "Variable might have not been defined" in inspection). Created a PR for an obvious one, the rest would need a closer look for fixing.

**Comment by sreichel** [comment]
Another find of obviously dead code, like #419.

Both mehtod arent used in core and seems nobody uses them ... otherwise you could find something about it SE or somewhere else.

How to deal with? Just fix or remove?

**Comment by sreichel** [comment]
Yep, there are a lot of them ...

Im not sure, about fixing or just remove the whole method ... there are some that could not work and would produce a warning or fatal error (#419). This code is not used anywhere ... remove it.

**Comment by LeeSaferite** [comment]
@sreichel BTW, I've done the layout refactor, I just need to get a PR issued for it at some point.

**Comment by dng-dev** [comment]
i would be in with removing core modules!

**Comment by kkrieger85** [comment]
@sreichel @Flyingmana Is this list still WIP? Could you please update tasks? Maybe with references to other issues?

**Comment by sreichel** [comment]
@kkrieger85 Had no time during pasts weeks. I'll update ASAP.

**Comment by ADDISON74** [comment]
Excellent job. It is a pity for so much effort if the work is not completed.

**Comment by sreichel** [comment]
@ADDISON74 biggest part is done.  DOCblocks for Adminhtml would be a large PR. So i dont worry,. The only PR i'd like to see get merged is #249 ... (still needs testing)

**Comment by ADDISON74** [comment]
@sreichel - PR #249 is closed. What shall we do in this case? Re-open it?
